# fly.toml app configuration file generated for pos-feed-instagram on 2025-09-13T21:53:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pos-feed-instagram'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
