app = "pos-feed-instagram"
primary_region = "bog"

[build]

# Proceso principal: Flask
[processes.app]
  command = "python app.py"

# Proceso secundario: Scheduler
[processes.scheduler]
  command = "python scheduler.py"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1  # al menos 1 máquina corriendo para el app
