app = "video-extractor"

[build]
  image = "video-extractor" # Fly lo construirá desde Dockerfile

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[deploy]
  release_command = ""
